#!/bin/sh
#
# This is an example script that sets the root pasword to a given
# default.

# Note: depending on your version of passwd, chpasswd can use the -e
# flag to handle en encrypted password. you probably want to use that.

cat $(dirname $0)/confdata/defaultpasswords | chroot $TARGET chpasswd

