#!/bin/bash

#Add sshkeys in vm's

#GWM_SSHKEYS="/usr/share/ganeti/misc/sshkeys.py"
#GWM_HOST="192.168.2.13:9869"
GWM_HOST=$HOSTNAME
instance=$INSTANCE_NAME

end_args=$instance
TMPFILE="$TARGET/tmp/$instance"

#install openssh server
#apt-get install openssh-server -y

mkdir $TARGET/root/.ssh
#curl -X GET -d "username=superuser&password=Gomeg4ganeti&instance_name=${instance}" $GWM_HOST/keys/template > $TMPFILE
curl -X GET -d "username=${USERNAME}&password=${PASSWORD}&instance_name=${instance}" $GWM_HOST/keys/template > $TMPFILE

if [ $? -eq 0 ] # Did the command work?
then # Success
    cat $TMPFILE > $TARGET/root/.ssh/authorized_keys
    rm -rf $TMPFILE
else # Fail
     cat $TMPFILE > $TARGET/root/response
     echo "An error occured. Error: SSH key file creation was failed"
     rm -rf $TMPFILE
fi


